
var closerToFinish = 1, closerToStart = 2
var fastEnemy = 3, slowEnemy = 4
var strongEnemy = 5, weakEnemy = 6
var cheapEnemy = 7, expensiveEnemy = 8
var randomEnemy = 9

var towerTypes = [
	{
		name: 'Archer tower',
		type: 0,
		targetting: closerToFinish,
		cost: 125,
		damage: 10,
		range: 2.5,
		attackSpeed: 3,
		currentAttackWait: 0,
		bullet: 2,
		target: -1,
		index: 0,
		x: 0,
		y: 0,
		divShift: 0.5,
		size: '85%',
		level: 1,
		lineHeight: 0.8,
		description: 'Archers are faster then guns',		
		img: '#|#\n-U-\n/---\\'
	},
	{
		name: 'Light gun tower',
		type: 1,
		targetting: closerToFinish,
		cost: 150,
		damage: 20,
		range: 3,
		attackSpeed: 2,
		currentAttackWait: 0,
		bullet: 1,
		target: -1,
		index: 0,
		x: 0,
		y: 0,
		divShift: 0.65,
		level: 1,
		size: '55%', //font-size
		lineHeight: 1, //line-height
		description: 'Good tower: has balanced characteristics',
		img: '_^_\n/---\\\n|L I|\n|===|\n|_O_|'
	},
	{
		name: 'Heavy gun tower',
		type: 2,
		targetting: closerToFinish,
		cost: 200,
		damage: 45,
		range: 3.5,
		attackSpeed: 0.5,
		currentAttackWait: 0,
		bullet: 3,
		target: -1,
		index: 0,
		x: 0,
		y: 0,
		divShift: 0.6,
		size: '50%',
		level: 1,
		lineHeight: 0.8,
		description: 'This is real heavy artillery',
		img: 'FFFFF\n\\-O-O-/\n|HHH|\n|HHH|\n//HHH\\\\\n|__U__|'
	},
	{
		name: 'Magic crystal',
		type: 3,
		targetting: closerToFinish,
		cost: 150,
		damage: 16,
		range: 1.5,
		attackSpeed: 2,
		currentAttackWait: 0,
		bullet: 4,
		target: -1,
		index: 0,
		x: 0,
		y: 0,
		divShift: 0.6,
		size: '65%',
		level: 1,
		lineHeight: 0.8,
		description: 'Wanna see some magic?',
		img: '/\\\n/H\\\n\\T/\n/AA\\\n-------'
	},
]

var enemyTypes = [
	{
		name: 'bandit',
		cost: 4,
		health: 30,
		speed: 2,
		index: 0,
		x: 0,
		y: 0,
		size: '80%', //font-size
		lineHeight: 0.5, //line-height
		direction: 2,
		img: 'p\n [O~\n||',
		imgLeft: 'q\n~O] \n||',
		description: 'I need your money.',
		type: 0,
	},
	{
		name: 'warrior',
		cost: 7,
		health: 50,
		speed: 2,
		index: 0,
		x: 0,
		y: 0,
		size: '80%', //font-size
		lineHeight: 0.5, //line-height
		direction: 2,
		img: 'o\niU/\n||',
		imgLeft: 'o\n\\Ui\n||',
		description: 'Let the fight begin!',
		type: 1,
	},
	{
		name: 'berserk',
		cost: 7,
		health: 40,
		speed: 3,
		index: 0,
		x: 0,
		y: 0,
		size: '80%',
		lineHeight: 0.5,
		direction: 2,
		img: 'o\n-V/\n||',
		imgLeft: 'o\n\\V-\n||',
		description: 'Dangerous. Fast. Not yours.',
		type: 2,
	},
	{
		name: 'heavy warrior',
		cost: 8,
		health: 115,
		speed: 1.4,
		index: 0,
		x: 0,
		y: 0,
		size: '85%',
		lineHeight: 0.5,
		direction: 2,
		img: '<b>n\nOI/\n||</b>',
		imgLeft: '<b>n\n\\IO\n||</b>',
		description: 'Heavy but slow.',
		type: 3,
	},
	{
		name: 'soldier',
		cost: 8,
		health: 80,
		speed: 2.2,
		index: 0,
		x: 0,
		y: 0,
		size: '80%',
		lineHeight: 0.5,
		direction: 2,
		img: 'o\n\'Sj\n||',
		imgLeft: 'o\njS\'\n||',
		description: 'Sir? Yes sir!',
		type: 4,
	},
	{
		name: 'evil wolf',
		cost: 9,
		health: 65,
		speed: 3,
		index: 0,
		x: 0,
		y: 0,
		size: '75%',
		lineHeight: 0.7,
		direction: 2,
		img: '~==8&\n  \\\\ \\\\',
		imgLeft: '&8==~\n// //',
		description: 'Bow-wow!',
		type: 5,
	},	
	{
		name: 'skeleton',
		cost: 5,
		health: 65,
		speed: 1.5,
		index: 0,
		x: 0,
		y: 0,
		size: '70%',
		lineHeight: 0.5,
		direction: 2,
		img: 'c\n\'Y!\n||',
		imgLeft: 'c\n!Y\'\n||',
		description: 'Am I dead? No, I\'m undead.',
		type: 6,
	},
	{
		name: 'spiky monster',
		cost: 13,
		health: 180,
		speed: 1.4,
		index: 0,
		x: 0,
		y: 0,
		size: '85%',
		lineHeight: 0.6,
		direction: 2,
		img: '~-^^^v\n  I\\ I\\',
		imgLeft: 'v^^^-~\n/I /I',
		description: 'WRHRRHRH',
		type: 7,
	},
	{
		name: 'orc',
		cost: 9,
		health: 70,
		speed: 2,
		index: 0,
		x: 0,
		y: 0,
		size: '80%',
		lineHeight: 0.5,
		direction: 2,
		img: 'v\nF/\n||',
		imgLeft: 'v\n\\F\n||',
		description: 'Dark warrior',
		type: 8,
	},
	{
		name: 'ogre',
		cost: 20,
		health: 350,
		speed: 1,
		index: 0,
		x: 0,
		y: 0,
		size: '90%',
		lineHeight: 0.6,
		direction: 2,
		img: '<b>\'V\'\n/WI\n  || *</b>',
		imgLeft: '<b>\'V\'\nIW\\\n* ||  </b>',
		description: 'Strong, big, dangerous and hard to kill.',
		type: 9,
	},
	{
		name: 'ghost',
		cost: 11,
		health: 145,
		speed: 2.5,
		index: 0,
		x: 0,
		y: 0,
		size: '90%',
		lineHeight: 0.6,
		direction: 2,
		img: '(o \n\'U\'\n-',
		imgLeft: ' o)\n\'U\'\n-',
		description: 'Do you wanna call ghostbusters?',
		type: 10,
	},
	{
		name: 'stone monster',
		cost: 13,
		health: 275,
		speed: 1.5,
		index: 0,
		x: 0,
		y: 0,
		size: '90%',
		lineHeight: 0.6,
		direction: 2,
		img: '<b>Oo\n(W)\nII</b>',
		imgLeft: '<b>oO\n(W)\nII</b>',
		description: 'I am more then a rock.',
		type: 11,
	},
	{
		name: 'troll',
		cost: 11,
		health: 180,
		speed: 2,
		index: 0,
		x: 0,
		y: 0,
		size: '80%',
		lineHeight: 0.6,
		direction: 2,
		img: 'V\n{H/\n||',
		imgLeft: 'V\n\\H}\n||',
		description: 'Did you see troll face?',
		type: 12,
	},
	{
		name: 'cave troll',
		cost: 15,
		health: 200,
		speed: 2,
		index: 0,
		x: 0,
		y: 0,
		size: '80%',
		lineHeight: 0.6,
		direction: 2,
		img: '<b>V\n|H/\n||</b>',
		imgLeft: '<b>V\n\\H|\n||</b>',
		description: 'U?',
		type: 13,
	},
	{
		name: 'spider',
		cost: 18,
		health: 200,
		speed: 2.2,
		index: 0,
		x: 0,
		y: 0,
		size: '50%',
		lineHeight: 0.6,
		direction: 2,
		img: 'oo\n-=OOO=-\n// // \\\\ \\\\',
		imgLeft: 'oo\n-=OOO=-\n// // \\\\ \\\\',
		description: 'Real spider-mem',
		type: 14,
	},
	{
		name: 'sea crab',
		cost: 20,
		health: 250,
		speed: 1.7,
		index: 0,
		x: 0,
		y: 0,
		size: '55%',
		lineHeight: 0.65,
		direction: 2,
		img: 'oo\nj-=OOO=-c\n// // \\\\ \\\\',
		imgLeft: 'oo\nj-=OOO=-c\n// // \\\\ \\\\',
		description: 'Who lives in a pineapple under the sea?',
		type: 15,
	},
	{
		name: 'snake',
		cost: 20,
		health: 250,
		speed: 1.8,
		index: 0,
		x: 0,
		y: 0,
		size: '100%',
		lineHeight: 0.5,
		direction: 2,
		img: ' ~S\n~~s      ', 
		imgLeft: 'S~ \n      s~~', 
		description: 'Shhh...',
		type: 16,
	},
	{
		name: 'knight',
		cost: 20,
		health: 275,
		speed: 2.2,
		index: 0,
		x: 0,
		y: 0,
		size: '60%',
		lineHeight: 0.7,
		direction: 2,
		img: '&nbsp&nbsp&nbsp&nbspo/\n/=N|E=G\n&nbsp||&nbsp&nbsp|\\',
		imgLeft: '&nbsp&nbsp\o\nG=E|N=\\\n&nbsp/|&nbsp&nbsp||',
		description: 'Look at my horse! My horse is amazing!',
		type: 17,
	},
	{
		name: 'ballist',
		cost: 25,
		health: 500,
		speed: 1.4,
		index: 0,
		x: 0,
		y: 0,
		size: '100%',
		lineHeight: 0.5,
		direction: 2,
		img: '===>\no&nbspo',
		imgLeft: '<===\no&nbspo',
		description: 'Wroom, wroom!',	
		type: 18,
	},
	{
		name: 'ninja',
		cost: 17,
		health: 125,
		speed: 3.1,
		index: 0,
		x: 0,
		y: 0,
		size: '80%',
		lineHeight: 0.5,
		direction: 2,
		img: ' o!\n!H \n||',
		imgLeft: '!o \n H!\n||',
		description: 'Can you see me?',	
		type: 19,
	},
	{
		name: 'assault trooper',
		cost: 15,
		health: 225,
		speed: 2,
		index: 0,
		x: 0,
		y: 0,
		size: '100%',
		lineHeight: 0.5,
		direction: 2,
		img: 'o\n\'Sj\n||',
		imgLeft: 'o\n\'Sj\n||',
		description: 'Fire!',	
		type: 20,
	},
	{
		name: 'assassin',
		cost: 15,
		health: 285,
		speed: 2.3,
		index: 0,
		x: 0,
		y: 0,
		size: '100%',
		lineHeight: 0.5,
		direction: 2,
		img: 'p\n{V/\n||',
		imgLeft: 'q\n\\V}\n||',
		description: 'Master of kill',	
		type: 21,
	},
	{
		name: 'dead warrior',
		cost: 15,
		health: 370,
		speed: 2,
		index: 0,
		x: 0,
		y: 0,
		size: '90%',
		lineHeight: 0.5,
		direction: 2,
		img: 'v\niV/\n||',
		imgLeft: 'v\n\\Vi\n||',
		description: 'Kill! Destroy! AAA',	
		type: 22,
	},
	{
		name: 'catapult',
		cost: 18,
		health: 900,
		speed: 1.3,
		index: 0,
		x: 0,
		y: 0,
		size: '100%',
		lineHeight: 0.75,
		direction: 2,
		img: 'u__o\no--o',
		imgLeft: 'o__u\no--o',
		description: 'Aron don don!',	
		type: 23,
	},
	{
		name: 'heavy death warrior',
		cost: 15,
		health: 950,
		speed: 1.3,
		index: 0,
		x: 0,
		y: 0,
		size: '90%',
		lineHeight: 0.5,
		direction: 2,
		img: '<b>v\njV/\n||</b>',
		imgLeft: '<b>v\n\\Vj\n||</b>',
		description: 'Heavy footsteps of the dark...',	
		type: 24,
	},
	{
		name: 'mage',
		cost: 15,
		health: 1100,
		speed: 2,
		index: 0,
		x: 0,
		y: 0,
		size: '80%',
		lineHeight: 0.5,
		direction: 2,
		img: '<b>^\niH \n||</b>',
		imgLeft: '<b>^\n Hi\n||</b>',
		description: 'Modus ponens!',	
		type: 25,
	},	
	{
		name: 'death knight',
		cost: 15,
		health: 1250,
		speed: 2.5,
		index: 0,
		x: 0,
		y: 0,
		size: '90%',
		lineHeight: 0.5,
		direction: 2,
		img: '&nbsp&nbsp&nbspVo\n/=N|E=G\n&nbsp||&nbsp&nbsp|\\',
		imgLeft: '&nbspoV\nG=E|N=\\\n&nbsp/|&nbsp&nbsp||',
		description: 'My life for the Dark Lord',	
		type: 26,
	},
	{
		name: 'siege tower',
		cost: 25,
		health: 5000,
		speed: 1.2,
		index: 0,
		x: 0,
		y: 0,
		size: '80%',
		lineHeight: 0.5,
		direction: 2,
		img: '[-----]\n|___|\n|###|\n|___|\n|###|\n|___|\nO O',
		imgLeft: '[-----]\n|___|\n|###|\n|___|\n|###|\n|___|\nO O',
		description: 'Big war machine',	
		type: 27,
	},
	{
		name: 'dragon',
		cost: 50,
		health: 7500,
		speed: 1.4,
		index: 0,
		x: 0,
		y: 0,
		size: '85%',
		lineHeight: 0.75,
		direction: 2,
		img: '<b>^^\n       ^^^^^  ^o-\\\n~~==\\ / \\ /=/\n	  \\\\    \\\\</b>',
		imgLeft: '<b>        ^^\n/-o^  ^^^^^\n       \\=\\ / \\ /==~~\n	  //    //</b>',
		description: 'He is evil, bad, bad and evil.',
		type: 28,
	},
	{
		name: 'the dark lord',
		cost: 100,
		health: 17500,
		speed: 1.5,
		index: 0,
		x: 0,
		y: 0,
		size: '85%',
		lineHeight: 0.6,
		direction: 2,
		img: '<b>w\no\n\\Vn\n||</b>',
		imgLeft: '<b>w\no\nnV/\n||</b>',
		description: 'Fear of the dark...',	
		type: 29,
	},
]

var bulletTypes = [
	{
		damage: 0,
		img: '+',
		x: 0,
		y: 0,
		targetX: 0,
		targetY: 0,
		speed: 10,
		target: -1,
		prevCoord: 0
	},
	{
		damage: 0,
		img: '.',
		x: 0,
		y: 0,
		targetX: 0,
		targetY: 0,
		speed: 12,
		target: -1,
		prevCoord: 0
	},
	{
		damage: 0,
		img: 'o',
		x: 0,
		y: 0,
		targetX: 0,
		targetY: 0,
		speed: 15,
		target: -1,
		prevCoord: 0
	},
	{
		damage: 0,
		img: '>',
		x: 0,
		y: 0,
		targetX: 0,
		targetY: 0,
		speed: 8,
		target: -1,
		prevCoord: 0
	},
]
